nameOverride: ""
fullnameOverride: "showcase-ui"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: openshift-default
    route.openshift.io/termination: edge
  hosts:
    - host: showcase-ui-dev.apps.silver.devops.gov.bc.ca
      paths:
        - path: /
          pathType: Prefix
  tls: []

ui:
  name: showcase-ui
  image:
    repository: public.ecr.aws/k8o4d9r5/bcshowcase/ditp-showcase-creator-ui
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  port: 8080
  path: /
  env:
    NODE_ENV: development
    API_URL: "https://bcshowcase-api.dev.nborbit.ca/"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 80
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      internet: true
      apiServer:
        enabled: true
        namespace: ""
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  labels:
    app.kubernetes.io/name: showcase-ui
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/part-of: credential-showcase
    app.kubernetes.io/managed-by: helm
  
debug: true 