nameOverride: ""
fullnameOverride: ""

ui:
  name: showcase-ui
  image:
    repository: public.ecr.aws/k8o4d9r5/bcshowcase/ditp-showcase-creator-ui
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  port: 3050
  path: /
  env:
    NODE_ENV: development
    API_URL: "https://bcshowcase-api.dev.nborbit.ca/"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3050
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
  openshift:
    route:
      enabled: true
      path: "/"
      targetPort: http
      tls:
        enabled: true
        termination: edge
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  
debug: true 