{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "showcase-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.ui.labels."app.kubernetes.io/name" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "showcase-ui.labels" . | nindent 8 }}
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.ui.name }}
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        {{- with .Values.ui.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.ui.port }}
          name: http
        env:
        {{- range $key, $value := .Values.ui.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "credential-showcase.authtoken.secret.name" . }}
              key: token
        resources:
          {{- toYaml .Values.ui.resources | nindent 12 }}
      serviceAccountName: {{ if .Values.ui.serviceAccount.create }}{{ if .Values.ui.serviceAccount.name }}{{ .Values.ui.serviceAccount.name }}{{ else }}{{ $.Release.Name }}{{ end }}{{ end }}
{{- end }} 