{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "showcase-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.ui.labels."app.kubernetes.io/name" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }} 