name: Uninstall PR instance

on:
  pull_request:
    branches:
      - main
    paths:
      - "**"
    types:
      - closed

jobs:
  uninstall:
    name: Uninstall PR
    environment: development
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v4
      - name: Check out manifest repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}
          path: charts

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Uninstall via Helm
        continue-on-error: true
        run: |
          helm uninstall pr-${{ github.event.number }}-showcase-ui

      - name: Remove Openshift Objects
        continue-on-error: true
        run: |
          oc delete secret,pvc --selector "app.kubernetes.io/instance"=pr-${{ github.event.number }}-showcase-ui


  clean-ghcr:
    runs-on: ubuntu-22.04
    if: ${{ false }}
    name: Delete closed PR images
    steps:
      - name: Delete Images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: bcgov
          image-names: ditp-showcase-creator-ui
          image-tags: pr-${{ github.event.number }}
          cut-off: 1second
          token: ${{ secrets.GITHUB_TOKEN }}